[package]
name = "tcp"
version = "0.1.0"
authors = ["ono"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
pnet = "0.27"
